single_class = {
    "dwarf_grey": ("Cleric", "Fighter", "Thief", "Thief-Acrobat", "Mountebank"),
    "dwarf_hill": ("Cleric", "Fighter", "Thief", "Thief-Acrobat", "Mountebank"),
    "dwarf_mountain": ("Cleric", "Fighter", "Thief", "Thief-Acrobat", "Mountebank"),
    "elf_dark_male": ("Bard", "Cavalier", "Cleric", "Fighter", "Ranger", "Mage", "Savant", "Thief", "Thief-Acrobat",
                      "Mountebank"),
    "elf_dark_female": ("Bard", "Cavalier", "Cleric", "Fighter", "Ranger", "Mage", "Savant", "Thief", "Thief-Acrobat",
                        "Mountebank"),
    "elf_gray": ("Bard", "Cleric", "Druid", "Mystic", "Fighter", "Ranger", "Mage", "Savant", "Thief", "Thief-Acrobat"),
    "elf_half": ("Bard", "Cavalier", "Cleric", "Druid", "Mystic", "Fighter", "Ranger", "Mage", "Savant", "Thief",
                 "Thief-Acrobat", "Mountebank"),
    "elf_high": ("Bard", "Cavalier", "Cleric", "Druid", "Mystic", "Fighter", "Ranger", "Mage", "Savant", "Thief",
                 "Thief-Acrobat", "Mountebank"),
    "elf_wild": ("Druid", "Mystic", "Fighter", "Thief", "Thief-Acrobat"),
    "elf_wood": ("Bard", "Cleric", "Druid", "Mystic", "Fighter", "Ranger", "Mage", "Thief", "Thief-Acrobat",
                 "Mountebank"),
    "gnome_deep": ("Bard", "Cleric", "Fighter", "Illusionist", "Thief", "Thief-Acrobat", "Mountebank"),
    "gnome_forest": ("Bard", "Jester", "Druid", "Fighter", "Savant", "Thief", "Thief-Acrobat", "Mountebank"),
    "gnome_hill": ("Bard", "Cleric", "Fighter", "Illusionist", "Thief", "Thief-Acrobat", "Mountebank"),
    "halfling": ("Bard", "Jester", "Cleric", "Druid", "Mystic", "Fighter", "Thief", "Thief-Acrobat", "Mountebank"),
    "half_orc": ("Cleric", "Fighter", "Barbarian", "Thief", "Thief-Acrobat", "Mountebank"),
    "human": ("Bard", "Jester", "Cavalier", "Paladin", "Cleric", "Druid", "Mystic", "Fighter", "Barbarian", "Ranger",
              "Mage", "Illusionist", "Savant", "Thief", "Thief-Acrobat", "Mountebank"),
}
multi_class = {
    "dwarf": ("Cleric Fighter", "Cleric Thief", "Cleric Thief-Acrobat", "Fighter Mountebank", "Fighter Thief",
              "Fighter Thief-Acrobat"),
    "elf_dark": ("Cleric Fighter", "Cleric Fighter Mage", "Cleric Fighter Savant", "Cleric Mage", "Cleric Savant",
                 "Cleric Thief", "Cleric Thief-Acrobat", "Fighter Mage", "Fighter Mage Thief",
                 "Fighter Mage Thief-Acrobat", "Fighter Savant", "Fighter Savant Thief", "Fighter Savant Thief-Acrobat",
                 "Fighter Savant Mountebank", "Fighter Mountebank", "Fighter Thief", "Fighter Thief-Acrobat",
                 "Mage Mountebank", "Mage Thief", "Mage Thief-Acrobat"),
    "elf_gray": ("Cleric Fighter", "Cleric Fighter Mage", "Cleric Ranger", "Cleric Ranger Mage", "Cleric Mage",
                 "Cleric Savant", "Cleric Thief", "Cleric Thief-Acrobat", "Druid Ranger", "Fighter Mage Mountebank",
                 "Fighter Mage Thief", "Fighter Mage Thief-Acrobat", "Fighter Mountebank", "Fighter Savant Mountebank",
                 "Fighter Savant Thief", "Fighter Savant Thief-Acrobat", "Fighter Thief", "Fighter Thief-Acrobat",
                 "Mage Thief", "Mage Thief-Acrobat", "Mage Mountebank", "Savant Thief", "Savant Thief-Acrobat",
                 "Savant Mountebank"),
    "elf_high": ("Cleric Fighter", "Cleric Fighter Mage", "Cleric Fighter Savant", "Cleric Mage", "Cleric Ranger",
                 "Cleric Ranger Mage", "Cleric Ranger Savant", "Cleric Savant", "Cleric Thief", "Cleric Thief-Acrobat",
                 "Druid Ranger", "Fighter Mage", "Fighter Mage Thief", "Fighter Mage Thief-Acrobat",
                 "Fighter Mage Mountebank", "Fighter Mountebank", "Fighter Savant", "Fighter Savant Thief",
                 "Fighter Savant Thief-Acrobat", "Fighter Savant Mountebank", "Fighter Mountebank", "Fighter Thief",
                 "Fighter Thief-Acrobat", "Mage Thief", "Mage Thief-Acrobat", "Mage Mountebank", "Mystic Fighter",
                 "Mystic Fighter Mage", "Mystic Mage", "Mystic Ranger", "Mystic Savant", "Mystic Thief",
                 "Mystic Thief-Acrobat", "Ranger Mage", "Ranger Savant", "Savant Thief", "Savant Thief-Acrobat",
                 "Savant Mountebank"),
    "elf_wild": ("Fighter Thief", "Fighter Thief-Acrobat"),
    "elf_wood": ("Cleric Fighter", "Cleric Fighter Mage", "Cleric Ranger", "Cleric Ranger Mage", "Cleric Mage",
                 "Cleric Thief", "Cleric Thief-Acrobat", "Druid Ranger", "Fighter Mage Mountebank",
                 "Fighter Mage Thief", "Fighter Savant Thief-Acrobat", "Fighter Mountebank", "Fighter Thief",
                 "Fighter Thief-Acrobat", "Mage Thief", "Mage Thief-Acrobat", "Mage Mountebank", "Mystic Fighter",
                 "Mystic Fighter Mage", "Mystic Mage", "Mystic Ranger", "Mystic Thief", "Mystic Thief-Acrobat"),
    "gnome_deep": ("Cleric Fighter", "Cleric Thief", "Cleric Thief-Acrobat", "Fighter Illusionist",
                   "Fighter Mountebank", "Fighter Thief", "Fighter Thief-Acrobat", "Illusionist Mountebank",
                   "Illusionist Thief", "Illusionist Thief-Acrobat", "Jester Fighter"),
    "gnome_forest": ("Druid Fighter", "Druid Thief", "Druid Thief-Acrobat", "Fighter Savant", "Fighter Thief",
                     "Fighter Thief-Acrobat", "Illusionist Mountebank", "Jester Fighter", "Savant Thief",
                     "Savant Mountebank"),
    "gnome_hill": ("Cleric Fighter", "Cleric Thief", "Cleric Thief-Acrobat", "Druid Fighter", "Druid Thief",
                   "Druid Thief-Acrobat", "Fighter Mountebank", "Fighter Thief", "Fighter Thief-Acrobat",
                   "Jester Thief", "Jester Thief-Acrobat", "Mystic Fighter"),
    "halfling": ("Cleric Fighter", "Cleric Thief", "Cleric Thief-Acrobat", "Druid Fighter", "Druid Thief",
                 "Druid Thief-Acrobat", "Fighter Mountebank", "Fighter Thief", "Fighter Thief-Acrobat", "Jester Thief",
                 "Jester Thief-Acrobat", "Mystic Fighter"),
    "half-orc": ("Cleric Fighter", "Cleric Mountebank", "Cleric Thief", "Cleric Thief-Acrobat", "Fighter Mountebank",
                 "Fighter Thief", "Fighter Thief-Acrobat"),
}
