import sys

from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import Qt, pyqtSlot
# from PyQt5.QtWidgets import QApplication, QWizard, QPushButton, QButtonGroup, QLineEdit, QLabel, QGroupBox, \
#     QRadioButton, QGridLayout, QWizardPage

# from New_Char_Wizard import Ui_Wizard
from Adv_Dark_Deep.Char_Creation import roll_abilities, race_vs_classes, class_min_attribs


class Wizard(QtWidgets.QWizard):
    def __init__(self):
        super().__init__(parent=None)
        Wizard.setObjectName(self, "Wizard")
        Wizard.resize(self, 775, 485)

        self.firstPage = FirstPage(self)
        self.secondPage = Page2(self)
        self.thirdPage = Page3(self)
        self.fourthPage = Page4(self)

        self.addPage(FirstPage(self))
        self.addPage(Page2(self))
        self.addPage(Page3(self))
        self.addPage(Page4(self))


class FirstPage(QtWidgets.QWizardPage):
    def __init__(self, parent=None):
        super().__init__(parent=None)

        # self.FirstPage = QtWidgets.QWizardPage()
        # self.FirstPage.setObjectName("FirstPage")
        self.setTitle("Create a New Character")
        self.setSubTitle("This wizard will walk you through creating a character. It will help "
                         "you roll your character\'s attributes, pick a race and class, and provide your "
                         "initial hit points. ")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 257, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.Char_name_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Char_name_label.sizePolicy().hasHeightForWidth())
        self.Char_name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.Char_name_label.setFont(font)
        self.Char_name_label.setWordWrap(True)
        self.Char_name_label.setObjectName("Char_name_label")
        self.horizontalLayout.addWidget(self.Char_name_label)
        self.Char_name_label.setText("Character Name")
        self.Char_Name_Out_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Char_Name_Out_lineEdit.sizePolicy().hasHeightForWidth())
        self.Char_Name_Out_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.Char_Name_Out_lineEdit.setFont(font)
        self.Char_Name_Out_lineEdit.setObjectName("Char_Name_Out_lineEdit")
        self.horizontalLayout.addWidget(self.Char_Name_Out_lineEdit)

        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(10, 30, 641, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Rolling_Options_label = QtWidgets.QLabel(self.frame)
        self.Rolling_Options_label.setGeometry(QtCore.QRect(152, 10, 352, 149))
        self.Rolling_Options_label.setWordWrap(True)
        self.Rolling_Options_label.setObjectName("Rolling_Options_label")
        self.Rolling_Options_label.setText(
            "<html><head/><body><p>Attributes can be re-rolled; they will be saved when the wizard is "
            "finished.</p><p>*4d6, minus lowest: Four dice are rolled for each attribute, with the lowest value "
            "removed each time. </p><p>*3d6: Three dice are rolled for each attribute.</p><p>*2d6+6: Two dice are "
            "rolled for each attribute, adding six to the value. </p></body></html>")

        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 136, 114))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Roll_Attribs_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Roll_Attribs_pushButton.setObjectName("Roll_Attribs_pushButton")
        self.Roll_Attribs_pushButton.setText("Roll Attributes")

        self.verticalLayout.addWidget(self.Roll_Attribs_pushButton)
        self.Four_dice_radioButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Four_dice_radioButton.setChecked(True)
        self.Four_dice_radioButton.setObjectName("Four_dice_radioButton")
        self.Dice_Type_buttonGroup = QtWidgets.QButtonGroup()
        self.Dice_Type_buttonGroup.setObjectName("Dice_Type_buttonGroup")
        self.Dice_Type_buttonGroup.addButton(self.Four_dice_radioButton)
        self.verticalLayout.addWidget(self.Four_dice_radioButton)
        self.Four_dice_radioButton.setText("4d6, drop lowest")

        self.Three_dice_radioButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Three_dice_radioButton.setObjectName("Three_dice_radioButton")
        self.Dice_Type_buttonGroup.addButton(self.Three_dice_radioButton)
        self.verticalLayout.addWidget(self.Three_dice_radioButton)
        self.Three_dice_radioButton.setText("3d6")

        self.Two_dice_radioButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Two_dice_radioButton.setObjectName("Two_dice_radioButton")
        self.Dice_Type_buttonGroup.addButton(self.Two_dice_radioButton)
        self.verticalLayout.addWidget(self.Two_dice_radioButton)
        self.Two_dice_radioButton.setText("2d6+6")

        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setGeometry(QtCore.QRect(10, 220, 644, 64))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.STR_label = QtWidgets.QLabel(self.frame_2)
        self.STR_label.setWordWrap(True)
        self.STR_label.setObjectName("STR_label")
        self.verticalLayout_2.addWidget(self.STR_label)
        self.STR_Out_label = QtWidgets.QLabel(self.frame_2)
        self.STR_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.STR_Out_label.setText("")
        self.STR_Out_label.setObjectName("STR_Out_label")
        self.verticalLayout_2.addWidget(self.STR_Out_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.STR_label.setText("Normal Strength")
        self.Exceptional_STR_label = QtWidgets.QLabel(self.frame_2)
        self.Exceptional_STR_label.setWordWrap(True)
        self.Exceptional_STR_label.setObjectName("Exceptional_STR_label")
        self.verticalLayout_3.addWidget(self.Exceptional_STR_label)
        self.Exceptional_STR_label.setText("Exceptional Strength")
        self.STR_Out_label_2 = QtWidgets.QLabel(self.frame_2)
        self.STR_Out_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.STR_Out_label_2.setText("")
        self.STR_Out_label_2.setObjectName("STR_Out_label_2")
        self.verticalLayout_3.addWidget(self.STR_Out_label_2)

        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DEX_label = QtWidgets.QLabel(self.frame_2)
        self.DEX_label.setObjectName("DEX_label")
        self.verticalLayout_4.addWidget(self.DEX_label)
        self.DEX_label.setText("Dexterity")
        self.DEX_Out_label = QtWidgets.QLabel(self.frame_2)
        self.DEX_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.DEX_Out_label.setText("")
        self.DEX_Out_label.setObjectName("DEX_Out_label")
        self.verticalLayout_4.addWidget(self.DEX_Out_label)

        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.IQ_label = QtWidgets.QLabel(self.frame_2)
        self.IQ_label.setObjectName("IQ_label")
        self.verticalLayout_5.addWidget(self.IQ_label)
        self.IQ_label.setText("Intelligence")
        self.IQ_Out_label = QtWidgets.QLabel(self.frame_2)
        self.IQ_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.IQ_Out_label.setText("")
        self.IQ_Out_label.setObjectName("IQ_Out_label")
        self.verticalLayout_5.addWidget(self.IQ_Out_label)

        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.WIS_label = QtWidgets.QLabel(self.frame_2)
        self.WIS_label.setObjectName("WIS_label")
        self.verticalLayout_6.addWidget(self.WIS_label)
        self.WIS_label.setText("Wisdom")
        self.WIS_Out_label = QtWidgets.QLabel(self.frame_2)
        self.WIS_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.WIS_Out_label.setText("")
        self.WIS_Out_label.setObjectName("WIS_Out_label")
        self.verticalLayout_6.addWidget(self.WIS_Out_label)

        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CON_label = QtWidgets.QLabel(self.frame_2)
        self.CON_label.setObjectName("CON_label")
        self.verticalLayout_7.addWidget(self.CON_label)
        self.CON_label.setText("Constitution")
        self.CON_Out_label = QtWidgets.QLabel(self.frame_2)
        self.CON_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.CON_Out_label.setText("")
        self.CON_Out_label.setObjectName("CON_Out_label")
        self.verticalLayout_7.addWidget(self.CON_Out_label)

        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CHR_label = QtWidgets.QLabel(self.frame_2)
        self.CHR_label.setObjectName("CHR_label")
        self.verticalLayout_8.addWidget(self.CHR_label)
        self.CHR_label.setText("Charisma")
        self.CHR_Out_label = QtWidgets.QLabel(self.frame_2)
        self.CHR_Out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.CHR_Out_label.setText("")
        self.CHR_Out_label.setObjectName("CHR_Out_label")
        self.verticalLayout_8.addWidget(self.CHR_Out_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)


class Page2(QtWidgets.QWizardPage):
    def __init__(self, parent=None):
        super().__init__(parent=None)
        self.setTitle("Character Race & Gender")
        self.setSubTitle("Select a character race. If your game allows UnderDark races as "
                                      "player characters, click the checkbox to show those races. Also, "
                                      "select a gender for your character.")
        # self = QtWidgets.QWizardPage()
        # self.setObjectName("wizardPage_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.Human_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Human_radioButton.setChecked(True)
        self.Human_radioButton.setObjectName("Human_radioButton")
        self.Human_radioButton.setText("Human")
        self.Race_buttonGroup = QtWidgets.QButtonGroup()
        self.Race_buttonGroup.setObjectName("Race_buttonGroup")
        self.Race_buttonGroup.addButton(self.Human_radioButton)
        self.gridLayout.addWidget(self.Human_radioButton, 0, 0, 1, 1)

        self.Elf_Wild_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Elf_Wild_radioButton.setChecked(False)
        self.Elf_Wild_radioButton.setObjectName("Elf_Wild_radioButton")
        self.Elf_Wild_radioButton.setText("Elf, Wild")

        self.Race_buttonGroup.addButton(self.Elf_Wild_radioButton)
        self.gridLayout.addWidget(self.Elf_Wild_radioButton, 0, 1, 1, 1)
        self.Dwarf_Hill_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Dwarf_Hill_radioButton.setChecked(False)
        self.Dwarf_Hill_radioButton.setObjectName("Dwarf_Hill_radioButton")
        self.Dwarf_Hill_radioButton.setText("Dwarf, Hill")
        self.Race_buttonGroup.addButton(self.Dwarf_Hill_radioButton)
        self.gridLayout.addWidget(self.Dwarf_Hill_radioButton, 1, 0, 1, 1)

        self.Elf_Wood_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Elf_Wood_radioButton.setChecked(False)
        self.Elf_Wood_radioButton.setObjectName("Elf_Wood_radioButton")
        self.Elf_Wood_radioButton.setText("Elf, Wood")
        self.Race_buttonGroup.addButton(self.Elf_Wood_radioButton)
        self.gridLayout.addWidget(self.Elf_Wood_radioButton, 1, 1, 1, 1)

        self.Dwarf_Mountain_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Dwarf_Mountain_radioButton.setChecked(False)
        self.Dwarf_Mountain_radioButton.setObjectName("Dwarf_Mountain_radioButton")
        self.Dwarf_Mountain_radioButton.setText("Dwarf, Mountain")
        self.Race_buttonGroup.addButton(self.Dwarf_Mountain_radioButton)
        self.gridLayout.addWidget(self.Dwarf_Mountain_radioButton, 2, 0, 1, 1)

        self.Gnome_Forest_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Gnome_Forest_radioButton.setChecked(False)
        self.Gnome_Forest_radioButton.setObjectName("Gnome_Forest_radioButton")
        self.Gnome_Forest_radioButton.setText("Gnome, Forest")
        self.Race_buttonGroup.addButton(self.Gnome_Forest_radioButton)
        self.gridLayout.addWidget(self.Gnome_Forest_radioButton, 2, 1, 1, 1)

        self.Elf_Half_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Elf_Half_radioButton.setChecked(False)
        self.Elf_Half_radioButton.setObjectName("Elf_Half_radioButton")
        self.Elf_Half_radioButton.setText("Half-Elf")
        self.Race_buttonGroup.addButton(self.Elf_Half_radioButton)
        self.gridLayout.addWidget(self.Elf_Half_radioButton, 3, 0, 1, 1)

        self.Gnome_Hill_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Gnome_Hill_radioButton.setChecked(False)
        self.Gnome_Hill_radioButton.setObjectName("Gnome_Hill_radioButton")
        self.Gnome_Hill_radioButton.setText("Gnome, Hill")
        self.Race_buttonGroup.addButton(self.Gnome_Hill_radioButton)
        self.gridLayout.addWidget(self.Gnome_Hill_radioButton, 3, 1, 1, 1)

        self.Elf_Gray_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Elf_Gray_radioButton.setChecked(False)
        self.Elf_Gray_radioButton.setObjectName("Elf_Gray_radioButton")
        self.Elf_Gray_radioButton.setText("Elf, Gray")
        self.Race_buttonGroup.addButton(self.Elf_Gray_radioButton)
        self.gridLayout.addWidget(self.Elf_Gray_radioButton, 4, 0, 1, 1)

        self.Halfling_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Halfling_radioButton.setChecked(False)
        self.Halfling_radioButton.setObjectName("Halfling_radioButton")
        self.Halfling_radioButton.setText("Halfling")
        self.Race_buttonGroup.addButton(self.Halfling_radioButton)
        self.gridLayout.addWidget(self.Halfling_radioButton, 4, 1, 1, 1)

        self.Elf_High_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Elf_High_radioButton.setChecked(False)
        self.Elf_High_radioButton.setObjectName("Elf_High_radioButton")
        self.Elf_High_radioButton.setText("Elf, High")
        self.Race_buttonGroup.addButton(self.Elf_High_radioButton)
        self.gridLayout.addWidget(self.Elf_High_radioButton, 5, 0, 1, 1)

        self.Half_Orc_radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.Half_Orc_radioButton.setChecked(False)
        self.Half_Orc_radioButton.setObjectName("Half_Orc_radioButton")
        self.Half_Orc_radioButton.setText("Half-Orc")
        self.Race_buttonGroup.addButton(self.Half_Orc_radioButton)
        self.gridLayout.addWidget(self.Half_Orc_radioButton, 5, 1, 1, 1)

        self.horizontalLayout_7.addWidget(self.frame_4)
        self.UnderDark_groupBox = QtWidgets.QGroupBox(self)
        self.UnderDark_groupBox.setCheckable(True)
        self.UnderDark_groupBox.setChecked(False)
        self.UnderDark_groupBox.setObjectName("UnderDark_groupBox")
        self.UnderDark_groupBox.setTitle("UnderDark Races")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.UnderDark_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")

        self.Dwarf_Gray_radioButton = QtWidgets.QRadioButton(self.UnderDark_groupBox)
        self.Dwarf_Gray_radioButton.setEnabled(False)
        self.Dwarf_Gray_radioButton.setChecked(False)
        self.Dwarf_Gray_radioButton.setObjectName("Dwarf_Gray_radioButton")
        self.Dwarf_Gray_radioButton.setText("Dwarf, Gray")
        self.Race_buttonGroup.addButton(self.Dwarf_Gray_radioButton)
        self.verticalLayout_9.addWidget(self.Dwarf_Gray_radioButton)

        self.Elf_Dark_radioButton = QtWidgets.QRadioButton(self.UnderDark_groupBox)
        self.Elf_Dark_radioButton.setEnabled(False)
        self.Elf_Dark_radioButton.setChecked(False)
        self.Elf_Dark_radioButton.setObjectName("Elf_Dark_radioButton")
        self.Elf_Dark_radioButton.setText("Elf, Dark")
        self.Race_buttonGroup.addButton(self.Elf_Dark_radioButton)
        self.verticalLayout_9.addWidget(self.Elf_Dark_radioButton)

        self.Gnome_Deep_radioButton = QtWidgets.QRadioButton(self.UnderDark_groupBox)
        self.Gnome_Deep_radioButton.setEnabled(False)
        self.Gnome_Deep_radioButton.setChecked(False)
        self.Gnome_Deep_radioButton.setObjectName("Gnome_Deep_radioButton")
        self.Gnome_Deep_radioButton.setText("Gnome, Deep")
        self.Race_buttonGroup.addButton(self.Gnome_Deep_radioButton)
        self.verticalLayout_9.addWidget(self.Gnome_Deep_radioButton)
        self.horizontalLayout_7.addWidget(self.UnderDark_groupBox)

        self.Gender_groupBox = QtWidgets.QGroupBox(self)
        self.Gender_groupBox.setObjectName("Gender_groupBox")
        self.Gender_groupBox.setTitle("Gender")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Gender_groupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")

        self.Male_radioButton = QtWidgets.QRadioButton(self.Gender_groupBox)
        self.Male_radioButton.setChecked(True)
        self.Male_radioButton.setObjectName("Male_radioButton")
        self.Male_radioButton.setText("Male")

        self.Gender_buttonGroup = QtWidgets.QButtonGroup()
        self.Gender_buttonGroup.setObjectName("Gender_buttonGroup")
        self.Gender_buttonGroup.addButton(self.Male_radioButton)
        self.verticalLayout_16.addWidget(self.Male_radioButton)

        self.Female_radioButton = QtWidgets.QRadioButton(self.Gender_groupBox)
        self.Female_radioButton.setObjectName("Female_radioButton")
        self.Female_radioButton.setText("Female")
        self.Gender_buttonGroup.addButton(self.Female_radioButton)
        self.verticalLayout_16.addWidget(self.Female_radioButton)
        self.horizontalLayout_7.addWidget(self.Gender_groupBox)


class Page3(QtWidgets.QWizardPage):
    def __init__(self, parent=None):
        super().__init__(parent=None)
        # self = QtWidgets.QWizardPage()
        # self.setObjectName("wizardPage_3")
        self.setTitle("Class Selection")
        self.setSubTitle(
                                                 "Based on your attributes and race, the classes listed below are "
                                                 "available to your character. Certain races can also be multi-classed.")

        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_3 = QtWidgets.QFrame(self)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.First_Class_groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.First_Class_groupBox.setObjectName("First_Class_groupBox")
        self.First_Class_groupBox.setTitle("Primary Class")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.First_Class_groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")

        self.Bard_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Bard_radioButton.setEnabled(False)
        self.Bard_radioButton.setObjectName("Bard_radioButton")
        self.Bard_radioButton.setText("Bard")
        self.verticalLayout_18.addWidget(self.Bard_radioButton)

        self.Jester_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Jester_radioButton.setEnabled(False)
        self.Jester_radioButton.setObjectName("Jester_radioButton")
        self.Jester_radioButton.setText("Jester")
        self.verticalLayout_18.addWidget(self.Jester_radioButton)

        self.Cavalier_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Cavalier_radioButton.setEnabled(False)
        self.Cavalier_radioButton.setObjectName("Cavalier_radioButton")
        self.Cavalier_radioButton.setText("Cavalier")
        self.verticalLayout_18.addWidget(self.Cavalier_radioButton)

        self.Paladin_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Paladin_radioButton.setEnabled(False)
        self.Paladin_radioButton.setObjectName("Paladin_radioButton")
        self.Paladin_radioButton.setText("Paladin")
        self.verticalLayout_18.addWidget(self.Paladin_radioButton)

        self.Cleric_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Cleric_radioButton.setEnabled(False)
        self.Cleric_radioButton.setObjectName("Cleric_radioButton")
        self.Cleric_radioButton.setText("Cleric")
        self.verticalLayout_18.addWidget(self.Cleric_radioButton)

        self.Druid_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Druid_radioButton.setEnabled(False)
        self.Druid_radioButton.setObjectName("Druid_radioButton")
        self.Druid_radioButton.setText("Druid")
        self.verticalLayout_18.addWidget(self.Druid_radioButton)

        self.Mystic_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Mystic_radioButton.setEnabled(False)
        self.Mystic_radioButton.setObjectName("Mystic_radioButton")
        self.Mystic_radioButton.setText("Mystic")
        self.verticalLayout_18.addWidget(self.Mystic_radioButton)

        self.Fighter_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Fighter_radioButton.setEnabled(False)
        self.Fighter_radioButton.setObjectName("Fighter_radioButton")
        self.Fighter_radioButton.setText("Fighter")
        self.verticalLayout_18.addWidget(self.Fighter_radioButton)

        self.Barbarian_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Barbarian_radioButton.setEnabled(False)
        self.Barbarian_radioButton.setObjectName("Barbarian_radioButton")
        self.Barbarian_radioButton.setText("Barbarian")
        self.verticalLayout_18.addWidget(self.Barbarian_radioButton)

        self.Ranger_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Ranger_radioButton.setEnabled(False)
        self.Ranger_radioButton.setObjectName("Ranger_radioButton")
        self.Ranger_radioButton.setText("Ranger")
        self.verticalLayout_18.addWidget(self.Ranger_radioButton)

        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Mage_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Mage_radioButton.setEnabled(False)
        self.Mage_radioButton.setObjectName("Mage_radioButton")
        self.Mage_radioButton.setText("Mage")
        self.verticalLayout_17.addWidget(self.Mage_radioButton)

        self.Illusionist_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Illusionist_radioButton.setEnabled(False)
        self.Illusionist_radioButton.setObjectName("Illusionist_radioButton")
        self.Illusionist_radioButton.setText("Illusionist")
        self.verticalLayout_17.addWidget(self.Illusionist_radioButton)

        self.Savant_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Savant_radioButton.setEnabled(False)
        self.Savant_radioButton.setObjectName("Savant_radioButton")
        self.Savant_radioButton.setText("Savant")
        self.verticalLayout_17.addWidget(self.Savant_radioButton)

        self.Thief_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Thief_radioButton.setEnabled(False)
        self.Thief_radioButton.setObjectName("Thief_radioButton")
        self.Thief_radioButton.setText("Thief")
        self.verticalLayout_17.addWidget(self.Thief_radioButton)

        self.Thief_Acrobat_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Thief_Acrobat_radioButton.setEnabled(False)
        self.Thief_Acrobat_radioButton.setObjectName("Thief_Acrobat_radioButton")
        self.Thief_Acrobat_radioButton.setText("Thief-Acrobat")
        self.verticalLayout_17.addWidget(self.Thief_Acrobat_radioButton)

        self.Mountebank_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Mountebank_radioButton.setEnabled(False)
        self.Mountebank_radioButton.setObjectName("Mountebank_radioButton")
        self.Mountebank_radioButton.setText("Mountebank")
        self.verticalLayout_17.addWidget(self.Mountebank_radioButton)

        self.Assassin_radioButton = QtWidgets.QRadioButton(self.First_Class_groupBox)
        self.Assassin_radioButton.setEnabled(False)
        self.Assassin_radioButton.setObjectName("Assassin_radioButton")
        self.Assassin_radioButton.setText("Assassin")
        self.verticalLayout_17.addWidget(self.Assassin_radioButton)

        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.horizontalLayout_6.addWidget(self.First_Class_groupBox)
        self.Second_Class_groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.Second_Class_groupBox.setEnabled(False)
        self.Second_Class_groupBox.setObjectName("Second_Class_groupBox")
        self.Second_Class_groupBox.setTitle("Second Class")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Second_Class_groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")

        self.Bard_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Bard_radioButton_2.setObjectName("Bard_radioButton_2")
        self.Bard_radioButton_2.setText("Bard")
        self.verticalLayout_12.addWidget(self.Bard_radioButton_2)

        self.Jester_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Jester_radioButton_2.setObjectName("Jester_radioButton_2")
        self.Jester_radioButton_2.setText("Jester")
        self.verticalLayout_12.addWidget(self.Jester_radioButton_2)

        self.Cavalier_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Cavalier_radioButton_2.setObjectName("Cavalier_radioButton_2")
        self.Cavalier_radioButton_2.setText("Cavalier")
        self.verticalLayout_12.addWidget(self.Cavalier_radioButton_2)

        self.Paladin_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Paladin_radioButton_2.setObjectName("Paladin_radioButton_2")
        self.Paladin_radioButton_2.setText("Paladin")
        self.verticalLayout_12.addWidget(self.Paladin_radioButton_2)

        self.Cleric_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Cleric_radioButton_2.setObjectName("Cleric_radioButton_2")
        self.Cleric_radioButton_2.setText("Cleric")
        self.verticalLayout_12.addWidget(self.Cleric_radioButton_2)

        self.Druid_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Druid_radioButton_2.setObjectName("Druid_radioButton_2")
        self.Druid_radioButton_2.setText("Druid")
        self.verticalLayout_12.addWidget(self.Druid_radioButton_2)

        self.Mystic_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Mystic_radioButton_2.setObjectName("Mystic_radioButton_2")
        self.Mystic_radioButton_2.setText("Mystic")
        self.verticalLayout_12.addWidget(self.Mystic_radioButton_2)

        self.Fighter_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Fighter_radioButton_2.setObjectName("Fighter_radioButton_2")
        self.Fighter_radioButton_2.setText("Fighter")
        self.verticalLayout_12.addWidget(self.Fighter_radioButton_2)

        self.Barbarian_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Barbarian_radioButton_2.setObjectName("Barbarian_radioButton_2")
        self.Barbarian_radioButton_2.setText("Barbarian")
        self.verticalLayout_12.addWidget(self.Barbarian_radioButton_2)

        self.Ranger_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Ranger_radioButton_2.setObjectName("Ranger_radioButton_2")
        self.Ranger_radioButton_2.setText("Ranger")
        self.verticalLayout_12.addWidget(self.Ranger_radioButton_2)

        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Mage_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Mage_radioButton_2.setObjectName("Mage_radioButton_2")
        self.Mage_radioButton_2.setText("Mage")
        self.verticalLayout_13.addWidget(self.Mage_radioButton_2)

        self.Illusionist_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Illusionist_radioButton_2.setObjectName("Illusionist_radioButton_2")
        self.Illusionist_radioButton_2.setText("Illusionist")
        self.verticalLayout_13.addWidget(self.Illusionist_radioButton_2)

        self.Savant_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Savant_radioButton_2.setObjectName("Savant_radioButton_2")
        self.Savant_radioButton_2.setText("Savant")
        self.verticalLayout_13.addWidget(self.Savant_radioButton_2)

        self.Thief_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Thief_radioButton_2.setObjectName("Thief_radioButton_2")
        self.Thief_radioButton_2.setText("Thief")
        self.verticalLayout_13.addWidget(self.Thief_radioButton_2)

        self.Thief_Acrobat_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Thief_Acrobat_radioButton_2.setObjectName("Thief_Acrobat_radioButton_2")
        self.Thief_Acrobat_radioButton_2.setText("Thief-Acrobat")
        self.verticalLayout_13.addWidget(self.Thief_Acrobat_radioButton_2)

        self.Mountebank_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Mountebank_radioButton_2.setObjectName("Mountebank_radioButton_2")
        self.Mountebank_radioButton_2.setText("Mountebank")
        self.verticalLayout_13.addWidget(self.Mountebank_radioButton_2)

        self.Assassin_radioButton_2 = QtWidgets.QRadioButton(self.Second_Class_groupBox)
        self.Assassin_radioButton_2.setObjectName("Assassin_radioButton_2")
        self.Assassin_radioButton_2.setText("Assassin")
        self.verticalLayout_13.addWidget(self.Assassin_radioButton_2)

        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.horizontalLayout_6.addWidget(self.Second_Class_groupBox)
        self.Third_Class_groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.Third_Class_groupBox.setEnabled(False)
        self.Third_Class_groupBox.setObjectName("Third_Class_groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Third_Class_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")

        self.Bard_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Bard_radioButton_3.setObjectName("Bard_radioButton_3")
        self.Bard_radioButton_3.setText("Bard")
        self.verticalLayout_14.addWidget(self.Bard_radioButton_3)

        self.Jester_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Jester_radioButton_3.setObjectName("Jester_radioButton_3")
        self.Jester_radioButton_3.setText("Jester")
        self.verticalLayout_14.addWidget(self.Jester_radioButton_3)

        self.Cavalier_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Cavalier_radioButton_3.setObjectName("Cavalier_radioButton_3")
        self.Cavalier_radioButton_3.setText("Cavalier")
        self.verticalLayout_14.addWidget(self.Cavalier_radioButton_3)

        self.Paladin_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Paladin_radioButton_3.setObjectName("Paladin_radioButton_3")
        self.Paladin_radioButton_3.setText("Paladin")
        self.verticalLayout_14.addWidget(self.Paladin_radioButton_3)

        self.Cleric_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Cleric_radioButton_3.setObjectName("Cleric_radioButton_3")
        self.Cleric_radioButton_3.setText("Cleric")
        self.verticalLayout_14.addWidget(self.Cleric_radioButton_3)

        self.Druid_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Druid_radioButton_3.setObjectName("Druid_radioButton_3")
        self.Druid_radioButton_3.setText("Druid")
        self.verticalLayout_14.addWidget(self.Druid_radioButton_3)

        self.Mystic_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Mystic_radioButton_3.setObjectName("Mystic_radioButton_3")
        self.Mystic_radioButton_3.setText("Mystic")
        self.verticalLayout_14.addWidget(self.Mystic_radioButton_3)

        self.Fighter_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Fighter_radioButton_3.setObjectName("Fighter_radioButton_3")
        self.Fighter_radioButton_3.setText("Fighter")
        self.verticalLayout_14.addWidget(self.Fighter_radioButton_3)

        self.Barbarian_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Barbarian_radioButton_3.setObjectName("Barbarian_radioButton_3")
        self.Barbarian_radioButton_3.setText("Barbarian")
        self.verticalLayout_14.addWidget(self.Barbarian_radioButton_3)

        self.Ranger_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Ranger_radioButton_3.setObjectName("Ranger_radioButton_3")
        self.Ranger_radioButton_3.setText("Ranger")
        self.verticalLayout_14.addWidget(self.Ranger_radioButton_3)

        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Mage_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Mage_radioButton_3.setObjectName("Mage_radioButton_3")
        self.Mage_radioButton_3.setText("Mage")
        self.verticalLayout_15.addWidget(self.Mage_radioButton_3)

        self.Illusionist_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Illusionist_radioButton_3.setObjectName("Illusionist_radioButton_3")
        self.Illusionist_radioButton_3.setText("Illusionist")
        self.verticalLayout_15.addWidget(self.Illusionist_radioButton_3)

        self.Savant_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Savant_radioButton_3.setObjectName("Savant_radioButton_3")
        self.Savant_radioButton_3.setText("Savant")
        self.verticalLayout_15.addWidget(self.Savant_radioButton_3)

        self.Thief_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Thief_radioButton_3.setObjectName("Thief_radioButton_3")
        self.Thief_radioButton_3.setText("Thief")
        self.verticalLayout_15.addWidget(self.Thief_radioButton_3)

        self.Thief_Acrobat_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Thief_Acrobat_radioButton_3.setObjectName("Thief_Acrobat_radioButton_3")
        self.Thief_Acrobat_radioButton_3.setText("Thief-Acrobat")
        self.verticalLayout_15.addWidget(self.Thief_Acrobat_radioButton_3)

        self.Mountebank_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Mountebank_radioButton_3.setObjectName("Mountebank_radioButton_3")
        self.Mountebank_radioButton_3.setText("Mountebank")
        self.verticalLayout_15.addWidget(self.Mountebank_radioButton_3)

        self.Assassin_radioButton_3 = QtWidgets.QRadioButton(self.Third_Class_groupBox)
        self.Assassin_radioButton_3.setObjectName("Assassin_radioButton_3")
        self.Assassin_radioButton_3.setText("Assassin")
        self.verticalLayout_15.addWidget(self.Assassin_radioButton_3)

        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.horizontalLayout_6.addWidget(self.Third_Class_groupBox)
        self.verticalLayout_11.addWidget(self.frame_3)


class Page4(QtWidgets.QWizardPage):
    def __init__(self, parent=None):
        super().__init__(parent=None)
        # self.wizardPage_4 = QtWidgets.QWizardPage()
        # self.wizardPage_4.setObjectName("wizardPage_4")
        self.setTitle("Wrap-Up")
        self.setSubTitle("Click \"Finish\" to complete the basics of your character.")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Finish_Out_label = QtWidgets.QLabel(self)
        self.Finish_Out_label.setWordWrap(True)
        self.Finish_Out_label.setObjectName("Finish_Out_label")
        self.Finish_Out_label.setText("<html><head/><body><p>Your character\'s information will be moved to a character sheet. In addition, your character\'s hit points, initial money, etc. will be auto-generated and added to the character sheet as well.<br/><br/></p></body></html>")
        self.verticalLayout_10.addWidget(self.Finish_Out_label)


def main():
    app = QtWidgets.QApplication(sys.argv)
    w = Wizard()
    w.show()
    app.exec_()


if __name__ == "__main__":
    sys.exit(main())
