# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Qt_Designer/Missing_Name.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_No_Name_Dialog(object):
    def setupUi(self, No_Name_Dialog):
        No_Name_Dialog.setObjectName("No_Name_Dialog")
        No_Name_Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(No_Name_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(No_Name_Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(No_Name_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(No_Name_Dialog)
        self.buttonBox.accepted.connect(No_Name_Dialog.accept)
        self.buttonBox.rejected.connect(No_Name_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(No_Name_Dialog)

    def retranslateUi(self, No_Name_Dialog):
        _translate = QtCore.QCoreApplication.translate
        No_Name_Dialog.setWindowTitle(_translate("No_Name_Dialog", "Missing Character Name"))
        self.label.setText(_translate("No_Name_Dialog", "You need to have a character name before saving."))
