import csv

melee_weapon_dict = {
    {'Weapon': 'Axe, battle', 'Cost': '5 g.p.', 'Weight(lbs.)': '7', 'Length': "4’", 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '7', 'Damage vs S/M': '1d8', 'Damage vs L': '1d8'},
    {'Weapon': 'Axe, hand', 'Cost': '1 g.p.', 'Weight(lbs.)': '5', 'Length': '18”', 'Two-Handed?': 'N',
     'Space(feet)': '1', 'Speed': '4', 'Damage vs S/M': '1d6', 'Damage vs L': '1d4'},
    {'Weapon': 'Bardiche', 'Cost': '7 g.p.', 'Weight(lbs.)': '12', 'Length': '5’', 'Two-Handed?': 'Y',
     'Space(feet)': '5', 'Speed': '9', 'Damage vs S/M': '2d4', 'Damage vs L': '3d4'},
    {'Weapon': 'Bec de corbin', 'Cost': '6 g.p.', 'Weight(lbs.)': '10', 'Length': '6’', 'Two-Handed?': 'Y',
     'Space(feet)': '6', 'Speed': '9', 'Damage vs S/M': '1d8', 'Damage vs L': '1d6'},
    {'Weapon': 'Bill-guisarme', 'Cost': '6 g.p.', 'Weight(lbs.)': '15', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '10', 'Damage vs S/M': '2d4', 'Damage vs L': '1d10'},
    {'Weapon': 'Caltrop', 'Cost': '2 s.p.', 'Weight(lbs.)': '3', 'Length': 'n/a', 'Two-Handed?': 'n/a',
     'Space(feet)': 'n/a', 'Speed': 'n/a', 'Damage vs S/M': '1', 'Damage vs L': '1d2'},
    {'Weapon': 'Club', 'Cost': 'n/a', 'Weight(lbs.)': '3', 'Length': '3’', 'Two-Handed?': 'N', 'Space(feet)': '3',
     'Speed': '4', 'Damage vs S/M': '1d6', 'Damage vs L': '1d3'},
    {'Weapon': 'Dagger', 'Cost': '2 g.p.', 'Weight(lbs.)': '1', 'Length': '15”', 'Two-Handed?': 'N', 'Space(feet)': '1',
     'Speed': '2', 'Damage vs S/M': '1d4', 'Damage vs L': '1d3'},
    {'Weapon': 'Falchion', 'Cost': '10 g.p.', 'Weight(lbs.)': '7', 'Length': '3 1⁄2’', 'Two-Handed?': 'N',
     'Space(feet)': '3', 'Speed': '5', 'Damage vs S/M': '1d6+1', 'Damage vs L': '2d4'},
    {'Weapon': 'Fauchard', 'Cost': '3 g.p.', 'Weight(lbs.)': '6', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '8', 'Damage vs S/M': '1d6', 'Damage vs L': '1d8'},
    {'Weapon': 'Fauchard-fork', 'Cost': '8 g.p.', 'Weight(lbs.)': '8', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '8', 'Damage vs S/M': '1d8', 'Damage vs L': '1d10'},
    {'Weapon': 'Flail, footman’s', 'Cost': '3 g.p.', 'Weight(lbs.)': '15', 'Length': '4’', 'Two-Handed?': 'Y',
     'Space(feet)': '6', 'Speed': '7', 'Damage vs S/M': '1d6+1', 'Damage vs L': '2d4'},
    {'Weapon': 'Flail, horseman’s', 'Cost': '8 g.p.', 'Weight(lbs.)': '4', 'Length': '2’', 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '6', 'Damage vs S/M': '1d4+1', 'Damage vs L': '1d4+1'},
    {'Weapon': 'Garrote', 'Cost': '1 e.p.', 'Weight(lbs.)': '0.1', 'Length': '3’', 'Two-Handed?': 'Y',
     'Space(feet)': '1', 'Speed': '2', 'Damage vs S/M': '1d4', 'Damage vs L': '1d6'},
    {'Weapon': 'Glaive', 'Cost': '6 g.p.', 'Weight(lbs.)': '7', 'Length': '8’', 'Two-Handed?': 'Y', 'Space(feet)': '1',
     'Speed': '8', 'Damage vs S/M': '1d6', 'Damage vs L': '1d10'},
    {'Weapon': 'Glaive-guisarme', 'Cost': '10 g.p.', 'Weight(lbs.)': '10', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '1', 'Speed': '9', 'Damage vs S/M': '2d4', 'Damage vs L': '2d6'},
    {'Weapon': 'Guisarme', 'Cost': '5 g.p.', 'Weight(lbs.)': '8', 'Length': '6’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '8', 'Damage vs S/M': '2d4', 'Damage vs L': '1d8'},
    {'Weapon': 'Guisarme-voulge', 'Cost': '7 g.p.', 'Weight(lbs.)': '15', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '10', 'Damage vs S/M': '2d4', 'Damage vs L': '2d4'},
    {'Weapon': 'Halberd', 'Cost': '9 g.p.', 'Weight(lbs.)': '17', 'Length': '5’', 'Two-Handed?': 'Y',
     'Space(feet)': '5', 'Speed': '9', 'Damage vs S/M': '1d10', 'Damage vs L': '2d6'},
    {'Weapon': 'Hammer, war', 'Cost': '1 g.p.', 'Weight(lbs.)': '5', 'Length': '18”', 'Two-Handed?': 'N',
     'Space(feet)': '2', 'Speed': '4', 'Damage vs S/M': '1d4+1', 'Damage vs L': '1d4'},
    {'Weapon': 'Hook fauchard', 'Cost': '6 g.p.', 'Weight(lbs.)': '8', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '9', 'Damage vs S/M': '1d4', 'Damage vs L': '1d4'},
    {'Weapon': 'Improvised weapon', 'Cost': 'n/a', 'Weight(lbs.)': '1-5', 'Length': '6”-5’', 'Two-Handed?': 'Y/N',
     'Space(feet)': '1-5', 'Speed': '5', 'Damage vs S/M': '1d6', 'Damage vs L': '1d3'},
    {'Weapon': 'Khopesh', 'Cost': '10 g.p.', 'Weight(lbs.)': '7', 'Length': '3 1⁄2’', 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '9', 'Damage vs S/M': '2d4', 'Damage vs L': '1d6'},
    {'Weapon': 'Knife', 'Cost': '1 g.p.', 'Weight(lbs.)': '0.5', 'Length': '1’', 'Two-Handed?': 'N', 'Space(feet)': '1',
     'Speed': '2', 'Damage vs S/M': '1d3', 'Damage vs L': '1d2'},
    {'Weapon': 'Lance, light', 'Cost': '6 g.p.', 'Weight(lbs.)': '5', 'Length': '10’', 'Two-Handed?': 'N',
     'Space(feet)': '1', 'Speed': '8', 'Damage vs S/M': '1d6', 'Damage vs L': '1d8'},
    {'Weapon': 'Lance, medium', 'Cost': '6 g.p.', 'Weight(lbs.)': '10', 'Length': '12’', 'Two-Handed?': 'N',
     'Space(feet)': '1', 'Speed': '7', 'Damage vs S/M': '1d6+1', 'Damage vs L': '2d6'},
    {'Weapon': 'Lance, heavy', 'Cost': '6 g.p.', 'Weight(lbs.)': '15', 'Length': '14’', 'Two-Handed?': 'N',
     'Space(feet)': '1', 'Speed': '6', 'Damage vs S/M': '1d8+2', 'Damage vs L': '3d6'},
    {'Weapon': 'Lucern hammer', 'Cost': '7 g.p.', 'Weight(lbs.)': '15', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '5', 'Speed': '9', 'Damage vs S/M': '2d4', 'Damage vs L': '1d6'},
    {'Weapon': 'Mace, footman’s', 'Cost': '8 g.p.', 'Weight(lbs.)': '6', 'Length': '2 ½’', 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '7', 'Damage vs S/M': '1d6+1', 'Damage vs L': '1d6'},
    {'Weapon': 'Mace, horseman’s', 'Cost': '4 g.p.', 'Weight(lbs.)': '4', 'Length': '18”', 'Two-Handed?': 'N',
     'Space(feet)': '2', 'Speed': '6', 'Damage vs S/M': '1d6', 'Damage vs L': '1d4'},
    {'Weapon': 'Mace, two-handed', 'Cost': '13 g.p.', 'Weight(lbs.)': '15', 'Length': '5’', 'Two-Handed?': 'Y',
     'Space(feet)': '6', 'Speed': '10', 'Damage vs S/M': '2d6', 'Damage vs L': '1d8'},
    {'Weapon': 'Man catcher', 'Cost': '25 g.p.', 'Weight(lbs.)': '8', 'Length': '8’', 'Two-Handed?': 'Y',
     'Space(feet)': '2', 'Speed': '7', 'Damage vs S/M': '1d2', 'Damage vs L': '1d2'},
    {'Weapon': 'Military fork', 'Cost': '4 g.p.', 'Weight(lbs.)': '7', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '1', 'Speed': '7', 'Damage vs S/M': '1d8', 'Damage vs L': '2d4'},
    {'Weapon': 'Military pick', 'Cost': '8 g.p.', 'Weight(lbs.)': '6', 'Length': '4’', 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '7', 'Damage vs S/M': '1d6+1', 'Damage vs L': '2d4'},
    {'Weapon': 'Morning star', 'Cost': '5 g.p.', 'Weight(lbs.)': '12', 'Length': '4’', 'Two-Handed?': 'N',
     'Space(feet)': '5', 'Speed': '7', 'Damage vs S/M': '2d4', 'Damage vs L': '1d6+1'},
    {'Weapon': 'Partisan', 'Cost': '10 g.p.', 'Weight(lbs.)': '8', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '3', 'Speed': '9', 'Damage vs S/M': '1d6', 'Damage vs L': '1d6+1'},
    {'Weapon': 'Pike', 'Cost': '3 g.p.', 'Weight(lbs.)': '8', 'Length': '18’', 'Two-Handed?': 'Y', 'Space(feet)': '1',
     'Speed': '13', 'Damage vs S/M': '1d6', 'Damage vs L': '1d12'},
    {'Weapon': 'Pole axe', 'Cost': '8 g.p.', 'Weight(lbs.)': '15', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '5', 'Speed': '8', 'Damage vs S/M': '1d8+1', 'Damage vs L': '2d6'},
    {'Weapon': 'Quarterstaff', 'Cost': '3 g.p.', 'Weight(lbs.)': '6', 'Length': '7’', 'Two-Handed?': 'Y',
     'Space(feet)': '3', 'Speed': '4', 'Damage vs S/M': '1d6', 'Damage vs L': '1d6'},
    {'Weapon': 'Ranseur', 'Cost': '4 g.p.', 'Weight(lbs.)': '5', 'Length': '8’', 'Two-Handed?': 'Y', 'Space(feet)': '1',
     'Speed': '8', 'Damage vs S/M': '2d4', 'Damage vs L': '2d4'},
    {'Weapon': 'Sap', 'Cost': '1 g.p.', 'Weight(lbs.)': '1-5', 'Length': '6”', 'Two-Handed?': 'N', 'Space(feet)': '1',
     'Speed': '2', 'Damage vs S/M': '1d2', 'Damage vs L': '1d2'},
    {'Weapon': 'Scimitar', 'Cost': '15 g.p.', 'Weight(lbs.)': '4', 'Length': '3’', 'Two-Handed?': 'N',
     'Space(feet)': '2', 'Speed': '4', 'Damage vs S/M': '1d8', 'Damage vs L': '1d8'},
    {'Weapon': 'Scythe', 'Cost': '18 g.p.', 'Weight(lbs.)': '10', 'Length': '7’', 'Two-Handed?': 'N',
     'Space(feet)': '6', 'Speed': '9', 'Damage vs S/M': '1d6', 'Damage vs L': '2d4'},
    {'Weapon': 'Sickle', 'Cost': '6 g.p.', 'Weight(lbs.)': '2', 'Length': '1’', 'Two-Handed?': 'N', 'Space(feet)': '3',
     'Speed': '3', 'Damage vs S/M': '1d4', 'Damage vs L': '1d6'},
    {'Weapon': 'Spear', 'Cost': '1 g.p.', 'Weight(lbs.)': '5', 'Length': '5’ - 12’', 'Two-Handed?': 'Y/N',
     'Space(feet)': '1', 'Speed': '7', 'Damage vs S/M': '1d6', 'Damage vs L': '1d8'},
    {'Weapon': 'Spetum', 'Cost': '3 g.p.', 'Weight(lbs.)': '5', 'Length': '8’', 'Two-Handed?': 'Y', 'Space(feet)': '1',
     'Speed': '8', 'Damage vs S/M': '1d6+1', 'Damage vs L': '2d6'},
    {'Weapon': 'Spiked buckler', 'Cost': '10 g.p.', 'Weight(lbs.)': '3', 'Length': '1’ (spike)', 'Two-Handed?': 'N',
     'Space(feet)': '2', 'Speed': '4', 'Damage vs S/M': '1d4', 'Damage vs L': '1d3'},
    {'Weapon': 'Sword, bastard', 'Cost': '25 g.p.', 'Weight(lbs.)': '10', 'Length': '4 ½’', 'Two-Handed?': 'Y/N',
     'Space(feet)': '4', 'Speed': '6', 'Damage vs S/M': '2d4', 'Damage vs L': '2d8'},
    {'Weapon': 'Sword, broad', 'Cost': '10 g.p.', 'Weight(lbs.)': '7', 'Length': '3 1⁄2’', 'Two-Handed?': 'N',
     'Space(feet)': '4', 'Speed': '5', 'Damage vs S/M': '2d4', 'Damage vs L': '1d6+1'},
    {'Weapon': 'Sword, long', 'Cost': '15 g.p.', 'Weight(lbs.)': '6', 'Length': '3 1⁄2’', 'Two-Handed?': 'N',
     'Space(feet)': '3', 'Speed': '5', 'Damage vs S/M': '1d8', 'Damage vs L': '1d12'},
    {'Weapon': 'Sword, short', 'Cost': '8 g.p.', 'Weight(lbs.)': '4', 'Length': '2’', 'Two-Handed?': 'N',
     'Space(feet)': '1', 'Speed': '3', 'Damage vs S/M': '1d6', 'Damage vs L': '1d8'},
    {'Weapon': 'Sword, two-handed*', 'Cost': '30 g.p.', 'Weight(lbs.)': '25', 'Length': '6’', 'Two-Handed?': 'Y',
     'Space(feet)': '6', 'Speed': '10', 'Damage vs S/M': '1d10', 'Damage vs L': '3d6'},
    {'Weapon': 'Trident', 'Cost': '4 g.p.', 'Weight(lbs.)': '5', 'Length': '6’', 'Two-Handed?': 'Y', 'Space(feet)': '1',
     'Speed': '7', 'Damage vs S/M': '1d6+1', 'Damage vs L': '3d4'},
    {'Weapon': 'Voulge', 'Cost': '2 g.p.', 'Weight(lbs.)': '12', 'Length': '8’', 'Two-Handed?': 'Y', 'Space(feet)': '2',
     'Speed': '10', 'Damage vs S/M': '2d4', 'Damage vs L': '2d4'},
    {'Weapon': 'Whip', 'Cost': '3 g.p.', 'Weight(lbs.)': '3', 'Length': '8’-20’', 'Two-Handed?': 'N',
     'Space(feet)': '14', 'Speed': '8', 'Damage vs S/M': '1d2', 'Damage vs L': '1'}
}


def convert_csv():
    with open("melee_weapons.csv") as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            print(row)


if __name__ == "__main__":
    convert_csv()
    print(melee_weapon_dict)
